//
//  AuthenticationOperation.swift
//  AltStore
//
//  Created by Riley Testut on 6/5/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

@preconcurrency import UIKit
import Foundation
import Network
import CoreData
@preconcurrency import AltSign

enum RevokeDecision: Sendable {
    case revokeSelected([ALTX509Certificate])
    case keepExisting
}

private class AnisetteDataProvider {
    private static let ANISETTE_VALID_DURATION: TimeInterval = 40.0

    private let context: AuthenticatedOperationContext
    private let progress: Progress?
    
    private var lastFetchedData: ALTAnisetteData?
    
    init(context: AuthenticatedOperationContext, progress: Progress?) {
        self.context = context
        self.progress = progress
    }
    
    func getAnisetteData(for session: ALTAppleAPISession? = nil) async throws -> ALTAnisetteData {
        let currentAnisette = session?.anisetteData ?? self.lastFetchedData
        
        if let currentAnisette = currentAnisette,
           currentAnisette.date.timeIntervalSinceNow >= -Self.ANISETTE_VALID_DURATION 
        {
            return currentAnisette
        }
        
        let anisetteData = try await FetchAnisetteDataOperation(context: self.context)
                                        .execute(parentProgress: self.progress)

        self.lastFetchedData = anisetteData
        return anisetteData
    }
}

typealias AuthenticationError = AuthenticationErrorCode.Error
enum AuthenticationErrorCode: Int, ALTErrorEnum, CaseIterable {
    case noTeam
    case noCertificate
    case teamSelectorError
    
    case missingPrivateKey
    case missingCertificate
    
    case certificateLimitReachedFree
    case certificateLimitReachedPaid
    
    var errorFailureReason: String {
        switch self {
        case .noTeam: return NSLocalizedString("Your Apple ID has no developer teams?", comment: "")
        case .noCertificate: return NSLocalizedString("The developer certificate could not be found.", comment: "")
        case .teamSelectorError: return NSLocalizedString("Error presenting team selector view.", comment: "")
        case .missingPrivateKey: return NSLocalizedString("The certificate's private key could not be found.", comment: "")
        case .missingCertificate: return NSLocalizedString("The certificate could not be found.", comment: "")
        case .certificateLimitReachedFree: return NSLocalizedString("You have already exhausted the limit of 1 certificate for free developer accounts. Please revoke the existing certificate and try again.", comment: "")
        case .certificateLimitReachedPaid: return NSLocalizedString("You have already exhausted the maximum certificates that can be generated by a paid developer account. Please revoke at least one certificate and try again.", comment: "")
        }
    }
}

struct AuthenticationResult {
    let team: ALTTeam
    let certificate: ALTCertificate?
    let session: ALTAppleAPISession
    let portalCertificates: [ALTX509Certificate]?
}

private struct SessionCache {
    let team: ALTTeam
    let session: ALTAppleAPISession
}

final class AuthenticationOperation: BaseStandaloneOperation<AuthenticatedOperationContext, AuthenticationResult>, @unchecked Sendable {
    
    private var appleIDEmailAddress: String?
    private var appleIDPassword: String?
    private var requiresPostAuthFlow = false

    /// Multi-account: `true` when this operation authenticates a specific (non-default) account
    /// (`context.accountID != nil`). Such flows must never touch the global `AuthManager` /
    /// `CertificateManager` state, which belongs to the default account.
    private var isTargetedAccountFlow: Bool { self.context.accountID != nil }

    /// Multi-account: whether this flow may update the global `AuthManager` / `CertificateManager`
    /// state. True for the untargeted flow and for a targeted flow of the *default* account (so a
    /// refresh that provisions a new certificate for the default account keeps the global copy in
    /// sync instead of leaving a stale certificate behind). Resolved once in `execute()`.
    private var updatesGlobalState = true
    
    let skipDeviceRegistration: Bool
    let skipCertificateProvisioning: Bool
    
    private lazy var anisetteDataProvider: AnisetteDataProvider = {
        AnisetteDataProvider(context: context, progress: self.progress)
    }()

    init(context: AuthenticatedOperationContext, skipDeviceRegistration: Bool = false, skipCertificateProvisioning: Bool = false) throws {
        self.skipDeviceRegistration = skipDeviceRegistration
        self.skipCertificateProvisioning = skipCertificateProvisioning

        try super.init(context: context)
        self.debugLog("""
        [AuthenticationOperation] Initialized with options:
          • skipDeviceRegistration: \(skipDeviceRegistration)
          • skipCertificateProvisioning: \(skipCertificateProvisioning)
        """)
    }
    
    // Main Pipeline Execution
    override func execute(parentProgress: Progress?) async throws -> AuthenticationResult {
        let startTime = CFAbsoluteTimeGetCurrent()
        debugLog("[AuthenticationOperation] execute() started")
        defer {
            let elapsed = CFAbsoluteTimeGetCurrent() - startTime
            debugLog("[AuthenticationOperation] execute() took: \(String(format: "%.3fs", elapsed))")
        }
        try await super.executePreconditionCheck(parentProgress: parentProgress)

        if let targetAccountID = self.context.accountID {
            let defaultAccountID = await DatabaseManager.shared.persistentContainer.performBackgroundTask { context in
                DatabaseManager.shared.activeAccount(in: context)?.identifier
            }
            self.updatesGlobalState = (targetAccountID == defaultAccountID)
        }

        let authResult = try await TaskChainCoalescerWithProgress.shared.coalesce(
            key: self.context.ignoresCachedCredentials
                ? "apple_auth:new:\(ObjectIdentifier(self.context).hashValue)"
                : "apple_auth:\(self.context.accountID ?? "default")",
            onProgress: { [weak self] progress in
                self?.setProgress(progress)
            }
        ) { [weak self] reportProgress -> AuthenticationResult in
            guard let self = self else { throw OperationError.cancelled }
            
            do {
                let result: AuthenticationResult

                // try to use cached session (per-account when a specific account is targeted)
                if !self.context.ignoresCachedCredentials,
                   let cached = self.loadCachedAuthState(),
                   (self.skipCertificateProvisioning || cached.certificate != nil)
                {
                    let session = cached.session
                    session.anisetteData = try await self.anisetteDataProvider.getAnisetteData(for: session)
                    
                    self.debugLog("[Authentication] Using cached session, team, certificate")
                    result = AuthenticationResult(
                        team: cached.team, 
                        certificate: cached.certificate, 
                        session: session, 
                        portalCertificates: self.context.portalCertificates
                    )
                } else {
                    result = try await self.startAuthentication(reportProgress: reportProgress)
                }
                
                try await self.finalizeAuthentication(result: .success(result))
                reportProgress(100)
                return result
            } catch {
                self.debugLog("[AuthenticationOperation] execute caught error during authentication: \(error). Cleaning up...")
                // if auth was good, but certs and others had errors don't signOut ourselves.
                // (A targeted per-account flow never signs out the default account.)
                if !self.isTargetedAccountFlow &&
                   !AuthManager.shared.hasStoredPassword &&
                   !AuthManager.shared.hasStoredXcodeToken
                {
                    AuthManager.shared.signOut()
                }
                try? await self.finalizeAuthentication(result: .failure(error))
                throw error
            }
        }
        
        self.context.team               = authResult.team
        self.context.signingCertificate = authResult.certificate
        self.context.session            = authResult.session
        self.context.portalCertificates = authResult.portalCertificates

        self.setProgress(100)
        return authResult
    }
    
    private func startAuthentication(reportProgress: @escaping @Sendable (Int64) -> Void) async throws -> AuthenticationResult {
        let (account, session) = if let silentResult = try await self.silentSignIn() {
            silentResult
        } else {
            try await self.authenticationLoop()
        }
        self.context.session = session
        if self.updatesGlobalState {
            AuthManager.shared.session = session
        }

        let authResult = try await self.provisioningLoop(
            account: account,
            session: session,
            reportProgress: reportProgress
        )
        
        return authResult
    }

    private func provisioningLoop(account: ALTAccount,
                                  session: ALTAppleAPISession,
                                  reportProgress: @escaping @Sendable (Int64) -> Void) async throws -> AuthenticationResult
    {
        
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        reportProgress(stepWeight)

        var resolvedTeam: ALTTeam?
        var resolvedCertificate: ALTCertificate?

        var isCertificateResolved = false
        var isDeviceRegistered = false

        while true {
            if self.isCancelled { throw OperationError.cancelled }

            do {
                // 1. Resolve Team & Save State
                if resolvedTeam == nil {
                    let team = try await self.fetchTeam(for: account, session: session)

                    self.context.team = team
                    if self.updatesGlobalState {
                        AuthManager.shared.team = team
                    }

                    try await self.saveTeamAndAccount(team)
                    reportProgress(stepWeight * 2)
                    resolvedTeam = team
                }

                guard let team = resolvedTeam else { continue }

                // 2. Resolve Certificate (Custom vs Developer Portal)
                if !isCertificateResolved {
                    let activeCert = self.storedSigningCertificate(for: team)
                    let isCustomCert = activeCert?.data.map { data in
                        let details = parseCertificate(derData: data)
                        return !details.subject.contains(team.identifier) && !details.issuer.contains(team.identifier)
                    } ?? false
                    if isCustomCert {
                        self.debugLog("[Authentication] Custom active certificate detected (Subject OU mismatch with Team ID '\(team.identifier)'). Bypassing portal fetch.")
                        resolvedCertificate = activeCert
                    } else if self.skipCertificateProvisioning {
                        resolvedCertificate = activeCert
                    } else {
                        let certificate = try await self.fetchCertificate(for: team, session: session)
                        if self.updatesGlobalState {
                            try CertificateManager.shared.setActiveCertificate(certificate)
                        }
                        self.persistSigningCertificate(certificate, accountID: self.context.accountID ?? team.account.identifier)
                        self.context.signingCertificate = certificate
                        resolvedCertificate = certificate
                    }
                    isCertificateResolved = true
                }

                guard isCertificateResolved else { continue }

                // 3. Register Current Device
                if !isDeviceRegistered {
                    if !self.skipDeviceRegistration {
                        self.verboseLog("[Authentication] Registering current device...")
                        let device = try await self.registerCurrentDevice(for: team, session: session)
                        self.debugLog("[Authentication] Registered current device UDID: \(device.identifier).")
                        reportProgress(stepWeight * 3)
                    }
                    isDeviceRegistered = true
                }

                return AuthenticationResult(
                    team: team,
                    certificate: resolvedCertificate,
                    session: session,
                    portalCertificates: self.context.portalCertificates
                )
                
            } catch {
                if self.isCancelled { throw OperationError.cancelled }

                self.debugLog("[AuthenticationOperation] provisioningLoop caught error: \(error)")
                let decision = await self.context.authenticationHandler.resolveProvisioningError(error)
                switch decision {
                    case .retry:
                        self.debugLog("[AuthenticationOperation] User chose retry in provisioningLoop")
                        continue
                    case .cancel:
                        self.debugLog("[AuthenticationOperation] User cancelled in provisioningLoop")
                        throw OperationError.cancelled
                }
            }
        }
    }
    
    private func silentSignIn() async throws -> (ALTAccount, ALTAppleAPISession)? {
        // "Add Account" forces a fresh sign-in so a new Apple ID can be entered rather than
        // silently re-authenticating the existing account's stored credentials.
        if self.context.ignoresCachedCredentials { return nil }
        let credentials = self.storedCredentials()

        // Try silent auth using Keychain Token
        if let adsid = credentials.adsid, 
           let xcodeToken = credentials.xcodeToken 
        {
            self.verboseLog("[AuthenticationOperation] Authenticating Apple ID with tokens...")

            do {
                let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
                let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

                return try await AuthManager.shared.authenticateWithToken(
                    adsid: adsid,
                    xcodeToken: xcodeToken, 
                    anisetteData: anisetteData, 
                    xcodeVersion: xcodeVersion
                )
            } catch {
                self.debugLog("[AuthenticationOperation] Token authentication failed: \(error)")
            }
        }
        
        // Try silent auth using Keychain Password
        if let appleID = credentials.emailAddress, 
           let password = credentials.password 
        {
            self.debugLog("[AuthenticationOperation] Authenticating Apple ID with saved password...")
            do {
                return try await self.authenticate(appleID: appleID, password: password)
            } catch {
                self.debugLog("[AuthenticationOperation] Saved password authentication failed: \(error)")
            }
        }

        return nil
    }

    private func authenticationLoop() async throws -> (account: ALTAccount, session: ALTAppleAPISession) {
        self.verboseLog("[Authentication] authenticationLoop: Requesting credentials...")
        let handler = self.context.authenticationHandler
        
        while true {
            let (appleID, password) = try await handler.credentials()
            if self.isCancelled { throw OperationError.cancelled }
            
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.debugLog("[Authentication] authenticationLoop: authenticate succeeded.")
                
                await handler.handleSignInResult(.success((account, session)))
                
                self.requiresPostAuthFlow = true
                return (account, session)
            } catch {
                self.debugLog("[Authentication] authenticationLoop: Attempt failed with error: \(error)")
                await handler.handleSignInResult(.failure(error))
            }
        }
    }
    
    private func authenticate(appleID: String, password: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        self.appleIDEmailAddress = appleID
        
        let anisetteData = try await self.anisetteDataProvider.getAnisetteData()
        let handler = self.context.authenticationHandler
        
        let xcodeVersion = await AnisetteConfigManager.shared.resolvedXcodeVersion()

        let (account, session) = try await AuthManager.shared.authenticate(
            appleID: appleID,
            password: password,
            anisetteData: anisetteData,
            xcodeVersion: xcodeVersion
        ) { completionHandler in

            Task.detached {
                do {
                    let code = try await handler.verificationCode()
                    completionHandler(code)
                } catch {
                    completionHandler(nil)
                }
            }
        }
        
        self.appleIDPassword = password
        if self.isTargetedAccountFlow {
            self.persistLoginTokens(adsid: session.dsid, xcodeToken: session.authToken)
        } else {
            AuthManager.shared.adsid = session.dsid
            AuthManager.shared.xcodeToken = session.authToken
            AuthManager.shared.currentAppleID = appleID
            AuthManager.shared.password = password
        }
        
        return (account, session)
    }


    private func finalizeAuthentication(result: Result<AuthenticationResult, Error>) async throws {
        self.verboseLog("[Authentication] finalizeAuthentication: Starting cleanup...")
        
        switch result {
            case .failure(let error):
                self.debugLog("[Authentication] finalizeAuthentication: Failure result - \(error.localizedDescription)")
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] finalizeAuthentication: invoked auth complete for .failure case...")
                
            case .success(let result):
                let team = result.team
                let certificate = result.certificate
                let session = result.session

                self.verboseLog("[Authentication] finalizeAuthentication: Authentication Success for team \(team.identifier) account.")
                do {
                    // Only (re)designate the default account/team when this is an interactive/default
                    // authentication (accountID == nil, e.g. sign-in or "add account"). A targeted refresh
                    // of a specific account must NOT change which account is the default for new installs,
                    // nor deactivate the other accounts -- they must keep refreshing independently.
                    try await self.saveTeamAndAccount(team, makeActive: !self.isTargetedAccountFlow)
                } catch {
                    self.debugLog("[Authentication] finalizeAuthentication: error occured when performing cleanup: \(error)")
                }
                self.verboseLog("[Authentication] finalizeAuthentication: Database updates completed.")

                // Multi-account: persist credentials + cache the authenticated state for the resolved
                // account (mirrored from the global store for the default account), so this account
                // can later be refreshed independently via its own per-account slots.
                let resolvedAccountID = self.context.accountID ?? team.account.identifier
                let emailAddress = self.appleIDEmailAddress ?? AuthManager.shared.currentAppleID ?? team.account.appleID
                self.persistLoginCredentials(emailAddress: emailAddress,
                                             password: self.appleIDPassword ?? (self.isTargetedAccountFlow ? nil : AuthManager.shared.password),
                                             adsid: session.dsid,
                                             xcodeToken: session.authToken,
                                             accountID: resolvedAccountID)
                if let certificate { self.persistSigningCertificate(certificate, accountID: resolvedAccountID) }
                Keychain.shared.cache(session: session, certificate: certificate, team: team, forAccount: resolvedAccountID)
                
                // Multi-account: SideStore itself is signed by exactly one account. Validating its
                // signature against any *other* account would always report a mismatch and push the
                // user into the "Resign SideStore" flow (or hang a headless background refresh).
                var sideStoreAccountID: String?
                if let dbContext = self.context.dbBackgroundContext {
                    sideStoreAccountID = await dbContext.perform {
                        let predicate = NSPredicate(format: "%K == %@", #keyPath(InstalledApp.bundleIdentifier), StoreApp.altstoreAppID)
                        return InstalledApp.first(satisfying: predicate, in: dbContext)?.resolvedSigningAccountID
                    }
                }
                let signsSideStore = (sideStoreAccountID == nil) || (sideStoreAccountID == resolvedAccountID)

                if let signingCertificate = certificate, !self.skipCertificateProvisioning, signsSideStore
                {
                    let signer = ALTSigner(team: team, certificate: signingCertificate)
                    let didResign = await self.validateCodeSign(signer: signer, session: session)
                    self.verboseLog("[Authentication] finalizeAuthentication: didResign = \(didResign)")
                    
                    if !didResign && self.requiresPostAuthFlow {
                        await self.context.authenticationHandler.resolvePostAuth()
                        self.verboseLog("[Authentication] finalizeAuthentication: post auth flow completed...")
                    }
                }
                
                await self.context.authenticationHandler.complete()
                self.verboseLog("[Authentication] finalizeAuthentication: invoked auth complete for .success case...")
        }
    }
}

// Persistence and Codesign Validity Check Helpers
private extension AuthenticationOperation {

    private func saveTeamAndAccount(_ altTeam: ALTTeam, makeActive: Bool = false) async throws {
        guard let context = self.context.dbBackgroundContext else {
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        try await context.perform {
            let account: Account
            let team: Team
            
            if let tempAccount = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), altTeam.account.identifier), in: context) {
                account = tempAccount
            } else {
                account = Account(altTeam.account, context: context)
            }
            
            if let tempTeam = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context) {
                team = tempTeam
            } else {
                team = Team(altTeam, account: account, context: context)
            }
            
            account.update(account: altTeam.account)

            if let providedEmailAddress = self.appleIDEmailAddress {
                account.appleID = providedEmailAddress
            }
            
            team.update(team: altTeam)
            
            if makeActive {
                // Account
                account.isActiveAccount = true
                let otherAccountsFetchRequest = Account.fetchRequest() as NSFetchRequest<Account>
                otherAccountsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Account.identifier), account.identifier)
                let otherAccounts = try context.fetch(otherAccountsFetchRequest)
                for otherAccount in otherAccounts {
                    otherAccount.isActiveAccount = false
                }

                // Team
                team.isActiveTeam = true
                let otherTeamsFetchRequest = Team.fetchRequest() as NSFetchRequest<Team>
                otherTeamsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Team.identifier), team.identifier)
                let otherTeams = try context.fetch(otherTeamsFetchRequest)
                for otherTeam in otherTeams {
                    otherTeam.isActiveTeam = false
                }

                let isSparseRestorePatched   = ProcessInfo().sparseRestorePatched
                let isAppLimitDisabled       = UserDefaults.standard.isAppLimitDisabled

                UserDefaults.standard.activeAppsLimit = nil
                // TODO: @mahee96: is the minimum ver match for ios 13.3.1 check required?
                //                 if so what is the app limit? As nil app limit specifies unlimited apps?!
                if team.type == .free {
                    if !isAppLimitDisabled && isSparseRestorePatched ||
                        isAppLimitDisabled && !isSparseRestorePatched 
                    {
                        UserDefaults.standard.activeAppsLimit = InstalledApp.freeAccountActiveAppsLimit
                    }
                }
            }
            
            try context.save()
        }
    }
    
    private func validateCodeSign(signer: ALTSigner, session: ALTAppleAPISession) async -> Bool {
        self.verboseLog("[Authentication] validateCodeSign: entering method")
        guard let appBundle = ALTApplication(fileURL: Bundle.Info.activeBundleURL), 
              let provisioningProfile = appBundle.provisioningProfile else 
        {
            self.verboseLog("[Authentication] validateCodeSign: Application bundle or provisioning profile nil, returning false")
            return false
        }
        
        let result = CodeSignValidator.validate(
            runningProfile: provisioningProfile,
            portalCertificates: self.context.portalCertificates,
            signerCertificate: signer.certificate.x509,
            signerTeam: signer.team
        )
        
        switch result {
            case .success:
                self.verboseLog("[Authentication] validateCodeSign: Validation succeeded, no resign required.")
                return false
                
            case .failure(let reason):
                self.debugLog("[Authentication] Signing certificate mismatch detected: \(reason)")
                
                // For Paid Developer accounts, if the certificate used to sign the current installation
                // is still active on Apple's portal (which shows as .privateKeyLost or .externalSigner),
                // we don't need to warn the user or force a resign.
                if signer.team.type != .free && (reason == .privateKeyLost || reason == .externalSigner) {
                    self.debugLog("[Authentication] Running certificate is still active on the Paid account portal. Skipping resign screen.")
                    return false
                }
                
                let handler = self.context.authenticationHandler
                do {
                    return try await handler.resolveResign(mismatchReason: reason, context: self.context)
                } catch {
                    self.verboseLog("[Authentication] validateCodeSign: error occured when handling resolveResign error: \(error)")
                    return false
                }
        }
    }
}


// Team, Certificate Resolution & Device Registration Helpers
private extension AuthenticationOperation {

    private func fetchTeam(for account: ALTAccount, session: ALTAppleAPISession) async throws -> ALTTeam {
        self.verboseLog("[Authentication] fetchTeam: Requesting teams from Apple...")
        let teams = try await DeveloperPortalService.shared.fetchTeams(for: account, session: session)
        
        let targetAccountID = self.context.accountID
        var preferredTeamID: String?
        if let dbContext = self.context.dbBackgroundContext {
            preferredTeamID = await dbContext.perform {
                if let targetAccountID = targetAccountID {
                    // When authenticating a specific account, prefer one of *its* teams so a
                    // different account's active team doesn't shadow it (and so multi-team accounts
                    // resolve without needing UI during a headless refresh).
                    let account = AccountManager.shared.account(targetAccountID, in: dbContext)
                    let team = account?.teams.first(where: { $0.isActiveTeam }) ?? account?.teams.first
                    return team?.identifier ?? DatabaseManager.shared.activeTeam(in: dbContext)?.identifier
                } else {
                    return DatabaseManager.shared.activeTeam(in: dbContext)?.identifier
                }
            }
        }
        
        let selectedTeam: ALTTeam
        if let preferredTeamID = preferredTeamID, let altTeam = teams.first(where: { $0.identifier == preferredTeamID }) {
            selectedTeam = altTeam
        } else if teams.count <= 1 {
            if let team = teams.first {
                selectedTeam = team
            } else {
                throw AuthenticationError(.noTeam)
            }
        } else {
            selectedTeam = try await self.context.authenticationHandler.resolveTeam(teams)
        }
        
        self.debugLog("[Authentication] fetchTeam completed successfully ('\(selectedTeam.name)').")
        return selectedTeam
    }

    private func fetchCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let portalCertificates = try await DeveloperPortalService.shared.fetchCertificates(team: team, session: session)
        self.context.portalCertificates = portalCertificates
        
        let mainBundleCertSerial = Bundle.main.object(forInfoDictionaryKey: Bundle.Info.certificateID) as? String
        
        if let activeCert = self.storedSigningCertificate(for: team),
           let certificate = portalCertificates.first(where: { $0.serialNumber == activeCert.serialNumber }) 
        {
            activeCert.machineIdentifier = certificate.machineIdentifier

            if let mainBundleCertSerial = mainBundleCertSerial, 
                mainBundleCertSerial.lowercased() != activeCert.serialNumber.lowercased() 
            {
                self.debugLog("[Authentication] Active certificate (\(activeCert.serialNumber)) and running bundle certificate (\(mainBundleCertSerial)) mismatch detected. Running Bundle Certificate is still active on the Paid account portal. Using active Keychain certificate.")
            }
            return activeCert
        }
        
        // TODO: @mahee96: we have moved away from machineID as password for certs, but external/thirdparty like iloader might not have, 
        //                 so we still support the machineId as fallback for now 
        if let mainBundleCertSerial = mainBundleCertSerial,
           let certificate = portalCertificates.first(where: { $0.serialNumber.lowercased() == mainBundleCertSerial.lowercased() }),
           let cert = CertificateManager.shared.getSignableCertificate(for: mainBundleCertSerial, fallbackPassword: certificate.machineIdentifier) 
        {
            cert.machineIdentifier = certificate.machineIdentifier
            self.debugLog("[Authentication] Using running bundle certificate (\(cert.serialNumber)) with valid private key from signable cache.")
            return cert
        }
        
        if portalCertificates.isEmpty {
            // No portalCertificates, so request a new one.
            return try await self.requestCertificate(for: team, session: session)
        } else {
            // We don't have private keys for any of the portalCertificates,
            // so we need to revoke one and create a new one.
            return try await self.replaceCertificate(portalCertificates: portalCertificates, for: team, session: session)
        }
    }

    private func requestCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let deviceName = await UIDevice.current.name
        let machineName: String = "SideStore - \(team.account.firstName)'s \(deviceName)"
        self.verboseLog("[Authentication] Requesting certificate for machineName '\(machineName)'...")

        do {
            let newPortalCertificate = try await DeveloperPortalService.shared.createCertificate(machineName: machineName, team: team, session: session)
            self.debugLog("[Authentication] Successfully requested new portal certificate (Serial: \(newPortalCertificate.serialNumber)).")
            
            // Apple's submitDevelopmentCSR response does not include raw certContent.
            // Fetch updated certificates list from portal to populate X509 certificate PEM data.
            let portalCertificates = try await DeveloperPortalService.shared.fetchCertificates(team: team, session: session)
            self.context.portalCertificates = portalCertificates

            let finalCert: ALTCertificate
            if let fullX509 = portalCertificates.first(where: { $0.serialNumber.lowercased() == newPortalCertificate.serialNumber.lowercased() }) {
                finalCert = ALTCertificate(x509: fullX509, privateKey: newPortalCertificate.privateKey)
            } else {
                finalCert = newPortalCertificate
            }

            return finalCert
        } catch {
            self.debugLog("[Authentication] requestCertificate: Failed with error: \(error)")
            let underlying = error as NSError
            if underlying.domain == ALTAppleAPIErrorDomain && 
               underlying.code == ALTAppleAPIError.tooManyCertificates.rawValue 
            {
                let friendlyError: AuthenticationError = (team.type == .free) 
                                        ? AuthenticationError(.certificateLimitReachedFree) 
                                        : AuthenticationError(.certificateLimitReachedPaid)

                let wrappedError = NSError(
                    domain: (friendlyError as NSError).domain,
                    code: (friendlyError as NSError).code,
                    userInfo: [
                        NSLocalizedDescriptionKey: friendlyError.localizedDescription,
                        NSLocalizedFailureReasonErrorKey: friendlyError.failureReason ?? "",
                        NSUnderlyingErrorKey: underlying
                    ]
                )
                throw wrappedError
            } else {
                throw error
            }
        }
    }

    private func replaceCertificate(portalCertificates: [ALTX509Certificate], for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        // Filter strictly for iOS Development certificates so Mac/Apple Development certs are never touched
        let iosCertificates = portalCertificates.filter { cert in
            let nameLower = cert.name.lowercased()
            return nameLower.contains("ios development") || nameLower.contains("iphone developer")
        }

        self.debugLog("[Authentication] replaceCertificate: Starting. Total certs on portal: \(portalCertificates.count), iOS Development certs: \(iosCertificates.count)")
        
        if iosCertificates.isEmpty {
            self.verboseLog("[Authentication] replaceCertificate: No iOS Development certificates found on portal. Requesting new...")
            return try await self.requestCertificate(for: team, session: session)
        }
        
        self.debugLog("[Authentication] replaceCertificate: Presenting revoke alert for \(iosCertificates.count) iOS Development cert(s)...")
        let action = try await self.context.authenticationHandler.resolveRevocation(certificates: iosCertificates, teamType: team.type)
        self.debugLog("[Authentication] replaceCertificate: User action was \(action)")
        switch action {
            case .keepExisting:
                self.verboseLog("[Authentication] replaceCertificate: Keeping existing, calling requestCertificate...")
                return try await self.requestCertificate(for: team, session: session)
                
            case .revokeSelected(let certsToRevoke):
                self.debugLog("[Authentication] replaceCertificate: Revoking \(certsToRevoke.count) selected certificate(s)...")
                var firstError: Error? = nil

                for certificate in certsToRevoke {
                    do {
                        self.verboseLog("[Authentication] replaceCertificate: Revoking certificate '\(certificate.machineName ?? certificate.name)' (Serial: \(certificate.serialNumber))...")
                        _ = try await DeveloperPortalService.shared.revokeCertificate(certificate, team: team, session: session)
                        self.verboseLog("[Authentication] replaceCertificate: Revoke succeeded.")
                    } catch {
                        self.debugLog("[Authentication] replaceCertificate: Revoke failed with error: \(error)")
                        if firstError == nil {
                            firstError = error
                        }
                    }
                }

                if let error = firstError {
                    self.debugLog("[Authentication] replaceCertificate: Error occurred during revocation, throwing...")
                    throw error
                } else {
                    self.debugLog("[Authentication] replaceCertificate: Selected certificates successfully revoked. Requesting new certificate...")
                    return try await self.requestCertificate(for: team, session: session)
                }
        }
    }
    
    @discardableResult
    private func registerCurrentDevice(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        self.debugLog("[Authentication] registerCurrentDevice starting...")
        var deviceUDID = try? await fetchUDID()
        if deviceUDID == nil || deviceUDID?.isEmpty == true || deviceUDID == "XXXXX-XXXX-XXXXX-XXXX" {
            deviceUDID = try? await fetchUDID(useStatic: true)
        }
        
        guard let udid = deviceUDID, !udid.isEmpty, udid != "XXXXX-XXXX-XXXXX-XXXX" else {
            self.debugLog("[Authentication] Failed to fetch device UDID.")
            throw OperationError.unknownUDID
        }
        self.debugLog("[Authentication] Fetched device UDID: \(udid). Fetching team devices...")
        
        let devices = try await DeveloperPortalService.shared.fetchDevices(for: team, types: [.iphone, .ipad], session: session)
        if let device = devices.first(where: { $0.identifier == udid }) {
            self.debugLog("[Authentication] Device '\(device.name)' (UDID: \(udid)) is registered on team.")
            return device
        } else {
            let deviceName = await MainActor.run { UIDevice.current.name }
            self.debugLog("[Authentication] Registering new device '\(deviceName)' (UDID: \(udid))...")
            let device = try await DeveloperPortalService.shared.registerDevice(name: UIDevice.current.name, identifier: udid, type: .iphone, team: team, session: session)
            self.debugLog("[Authentication] Device '\(device.name)' (UDID: \(udid)) successfully registered.")
            return device
        }
    }
}

// MARK: - Per-account credential storage
//
// When `context.accountID` is set, credentials and the cached session are stored/loaded from
// that account's isolated slots so multiple accounts can stay authenticated at once. When it is
// nil (the interactive "sign in / add account" flow and the default account), the upstream global
// stores (`AuthManager` / `CertificateManager`) are used, and -- once the account identifier is
// known -- the values are also mirrored into the per-account slots so the default account
// participates in per-account refresh.
private extension AuthenticationOperation {
    var targetAccountID: String? { self.context.accountID }

    /// The cached authenticated state for the account being authenticated, if still in memory.
    func loadCachedAuthState() -> (session: ALTAppleAPISession, team: ALTTeam, certificate: ALTCertificate?)? {
        if let accountID = self.targetAccountID {
            guard let session = Keychain.shared.cachedSession(forAccount: accountID),
                  let team = Keychain.shared.cachedTeam(forAccount: accountID) else { return nil }
            return (session, team, Keychain.shared.cachedCertificate(forAccount: accountID))
        } else {
            guard let session = AuthManager.shared.session,
                  let team = AuthManager.shared.team else { return nil }
            return (session, team, CertificateManager.shared.activeCertificate?.certificate)
        }
    }

    /// The stored login credentials for the account being authenticated.
    func storedCredentials() -> AccountCredentials {
        if let accountID = self.targetAccountID {
            return Keychain.shared.credentials(forAccount: accountID)
        } else {
            return AccountCredentials(
                emailAddress: AuthManager.shared.currentAppleID,
                password: AuthManager.shared.password,
                adsid: AuthManager.shared.adsid,
                xcodeToken: AuthManager.shared.xcodeToken,
                signingCertificate: Keychain.shared.signingCertificate,
                signingCertificatePassword: Keychain.shared.signingCertificatePassword
            )
        }
    }

    /// The signing certificate previously stored for the account being authenticated: the
    /// account's own slot for a targeted flow -- and for an "add account" sign-in, where the
    /// global active certificate belongs to the *previous* account and must not be inherited --
    /// the global active certificate otherwise.
    func storedSigningCertificate(for team: ALTTeam? = nil) -> ALTCertificate? {
        let accountID = self.targetAccountID ?? (self.context.ignoresCachedCredentials ? team?.account.identifier : nil)
        if let accountID {
            let credentials = Keychain.shared.credentials(forAccount: accountID)
            guard let data = credentials.signingCertificate else { return nil }
            return try? CertificateManager.parse(data, password: credentials.signingCertificatePassword)
        }
        return CertificateManager.shared.activeCertificate?.certificate
    }

    /// Persist the login tokens obtained during interactive authentication of a targeted account.
    func persistLoginTokens(adsid: String, xcodeToken: String) {
        guard let accountID = self.targetAccountID else { return }
        var credentials = Keychain.shared.credentials(forAccount: accountID)
        credentials.adsid = adsid
        credentials.xcodeToken = xcodeToken
        Keychain.shared.setCredentials(credentials, forAccount: accountID)
    }

    /// Persist the Apple ID + password + session tokens for the resolved account. Storing the
    /// dsid/authToken per-account lets that account later re-authenticate silently via token even
    /// when it was signed in through the default flow.
    func persistLoginCredentials(emailAddress: String, password: String?, adsid: String?, xcodeToken: String?, accountID: String) {
        var credentials = Keychain.shared.credentials(forAccount: accountID)
        credentials.emailAddress = emailAddress
        if let password = password { credentials.password = password }
        if let adsid = adsid { credentials.adsid = adsid }
        if let xcodeToken = xcodeToken { credentials.xcodeToken = xcodeToken }
        Keychain.shared.setCredentials(credentials, forAccount: accountID)
    }

    /// Persist the signing certificate for the resolved account (the default account's copy also
    /// lives in `CertificateManager`).
    func persistSigningCertificate(_ certificate: ALTCertificate, accountID: String) {
        let password = CertificateManager.shared.getPassword(for: certificate)
        guard let p12Data = try? CertificateManager.convert(certificate, password: password) else {
            self.debugLog("[Authentication] persistSigningCertificate: failed to export certificate for account \(accountID)")
            return
        }
        var credentials = Keychain.shared.credentials(forAccount: accountID)
        credentials.signingCertificate = p12Data
        credentials.signingCertificatePassword = password
        Keychain.shared.setCredentials(credentials, forAccount: accountID)
    }
}
